TL.Extensions/Engine/TL.Engine.Web/Models/ErrorViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using TL.Engine.Data.Entities.Reports;

namespace TL.Engine.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public int StatusCode { get; set; }

        public string ReturnUrl { get; set; }

        public string StatusMessage { get; set; }

        [Required(ErrorMessage = "Вы не представились")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Опишите проблему")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Нельзя отправить отчёт без ошибок!")]
        public string Message { get; set; }

        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Нельзя отправить пустой отчёт!")]
        public string StackTrace { get; set; }

        [Required(ErrorMessage = "На сколько проблема критична?")]
        public ReportPriority? Priority { get; set; }

        public DateTime Date { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Link/LinkViewModel.cs
using System.Collections.Generic;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class LinkViewModel
    {
        public string Url { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public IEnumerable<LinkViewModel> Items { get; set; }
        public bool HasDescription => !string.IsNullOrWhiteSpace(Description);
        public bool IsAvailable { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Link/LinkViewModelFactory.cs
using System.Linq;
using TL.Engine.SDK.Modularity.Items;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class LinkViewModelFactory
    {
        public LinkViewModel Create(LinkItem linkItem)
        {
            return new LinkViewModel()
            {
                Url = linkItem.Url,
                Name = linkItem.Name,
                Description = linkItem.Description,
                Items = linkItem.Items?.Select(li => new LinkViewModelFactory().Create(li)),
                IsAvailable = linkItem.IsAvailable
            };
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Links/LinksViewModel.cs
using System.Collections.Generic;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class LinksViewModel
    {
        public IEnumerable<LinkViewModel> Items { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Links/LinksViewModelFactory.cs
using ExtCore.Infrastructure;
using System.Collections.Generic;
using System.Linq;
using TL.Engine.SDK.Extensions;
using TL.Engine.SDK.Modularity;
using TL.Engine.SDK.Modularity.Items;
using TL.Engine.SDK.Services;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class LinksViewModelFactory
    {
        public LinksViewModel Create(IActivatorService activator, IEnumerable<string> roles, string property)
        {
            return new LinksViewModel()
            {
                Items = activator
                    .GetInstances<BaseMetadataWeb>()
                    .SelectMany(it => it.GetType().GetProperty(property).GetValue(it) as IEnumerable<LinkItem>)
                    .GetValidLinkItems(roles)
                    .OrderBy(mi => mi.Position)
                    .Select(mi => new LinkViewModelFactory().Create(mi))
            };
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Script/ScriptViewModel.cs
namespace TL.Engine.Web.ViewModels.Shared
{
    public class ScriptViewModel
    {
        public string Url { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Script/ScriptViewModelFactory.cs
using TL.Engine.SDK.Modularity.Items;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class ScriptViewModelFactory
    {
        public ScriptViewModel Create(ScriptItem script)
        {
            return new ScriptViewModel()
            {
                Url = script.Url
            };
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Scripts/ScriptsViewModel.cs
using System.Collections.Generic;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class ScriptsViewModel
    {
        public IEnumerable<ScriptViewModel> Scripts { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Scripts/ScriptsViewModelFactory.cs
using ExtCore.Infrastructure;
using System.Collections.Generic;
using System.Linq;
using TL.Engine.SDK.Modularity;
using TL.Engine.SDK.Modularity.Items;
using TL.Engine.SDK.Services;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class ScriptsViewModelFactory
    {
        public ScriptsViewModel Create(IActivatorService activator)
        {
            List<ScriptItem> scripts = new List<ScriptItem>();

            foreach (var extensionMetadata in activator.GetInstances<BaseMetadataWeb>(useCaching: true))
            {
                scripts.AddRange(extensionMetadata.ScriptItems);
            }

            return new ScriptsViewModel()
            {
                Scripts = scripts
                    .OrderBy(s => s.Position)
                    .Select(s => new ScriptViewModelFactory().Create(s))
            };
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Style/StyleViewModel.cs
namespace TL.Engine.Web.ViewModels.Shared
{
    public class StyleViewModel
    {
        public string Url { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Style/StyleViewModelFactory.cs
using TL.Engine.SDK.Modularity.Items;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class StyleViewModelFactory
    {
        public StyleViewModel Create(StyleItem style)
        {
            return new StyleViewModel()
            {
                Url = style.Url
            };
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Styles/StylesViewModel.cs
using System.Collections.Generic;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class StylesViewModel
    {
        public IEnumerable<StyleViewModel> Styles { get; set; }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewModels/Shared/Styles/StylesViewModelFactory.cs
using System.Collections.Generic;
using System.Linq;
using TL.Engine.SDK.Modularity;
using TL.Engine.SDK.Modularity.Items;
using TL.Engine.SDK.Services;

namespace TL.Engine.Web.ViewModels.Shared
{
    public class StylesViewModelFactory
    {
        public StylesViewModel Create(IActivatorService activator)
        {
            List<StyleItem> styles = new List<StyleItem>();

            foreach (var extensionMetadata in activator.GetInstances<BaseMetadataWeb>(useCaching: true))
            {
                styles.AddRange(extensionMetadata.StyleItems);
            }

            return new StylesViewModel()
            {
                Styles = styles
                    .OrderBy(ss => ss.Position)
                    .Select(ss => new StyleViewModelFactory().Create(ss))
            };
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TL.Engine.Web.Models;

namespace TL.Engine.Web.Controllers
{
    [Route("/error")]
    public class ErrorController : Controller
    {
        public ErrorController(ILogger<ErrorController> logger)
        {
            Logger = logger;
        }

        ILogger<ErrorController> Logger { get; }

        [HttpGet("{code}")]
        public IActionResult Index(int code)
        {
            var reExecute = HttpContext.Features.Get<IStatusCodeReExecuteFeature>();
            Logger.LogInformation($"Unexpected Status Code: {code}, OriginalPath: {reExecute?.OriginalPath ?? "not instance"}");
            return View(new ErrorViewModel
            {
                RequestId = null,
                ReturnUrl = Request.Headers["Referer"].ToString(),
                StatusCode = code
            });
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using TL.Engine.SDK.Services;
using TL.Engine.SDK.ViewComponents;
using TL.Engine.Web.ViewModels.Shared;

namespace TL.Engine.Web.ViewComponents
{
    public class NavbarViewComponent : ActivatorViewComponent
    {
        public NavbarViewComponent(IActivatorService activator) : base(activator)
        {
        }

        public IViewComponentResult Invoke()
        {
            return View(new LinksViewModelFactory()
                .Create(Activator, UserClaimsPrincipal
                .Claims
                .Where(c => c.Type == ClaimsIdentity.DefaultRoleClaimType)
                .Select(c => c.Value), "NavbarItems"));
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewComponents/ScriptsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TL.Engine.SDK.Services;
using TL.Engine.SDK.ViewComponents;
using TL.Engine.Web.ViewModels.Shared;

namespace TL.Engine.Web.ViewComponents
{
    public class ScriptsViewComponent : ActivatorViewComponent
    {
        public ScriptsViewComponent(IActivatorService activator) : base(activator)
        {
        }

        public IViewComponentResult Invoke()
        {
            return View(new ScriptsViewModelFactory().Create(Activator));
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using TL.Engine.SDK.Services;
using TL.Engine.SDK.ViewComponents;
using TL.Engine.Web.ViewModels.Shared;

namespace TL.Engine.Web.ViewComponents
{
    public class SidebarViewComponent : ActivatorViewComponent
    {
        public SidebarViewComponent(IActivatorService activator) : base(activator)
        {
        }

        public IViewComponentResult Invoke()
        {
            return View(new LinksViewModelFactory()
                .Create(Activator, UserClaimsPrincipal
                .Claims
                .Where(c => c.Type == ClaimsIdentity.DefaultRoleClaimType)
                .Select(c => c.Value), "SidebarItems"));
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/ViewComponents/StylesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TL.Engine.SDK.Services;
using TL.Engine.SDK.ViewComponents;
using TL.Engine.Web.ViewModels.Shared;

namespace TL.Engine.Web.ViewComponents
{
    public class StylesViewComponent : ActivatorViewComponent
    {
        public StylesViewComponent(IActivatorService activator) : base(activator)
        {
        }

        public IViewComponentResult Invoke()
        {
            return this.View(new StylesViewModelFactory().Create(Activator));
        }
    }
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Error.cshtml
@model TL.Engine.Web.Models.ErrorViewModel
@{
    var statusCode = Model.StatusCode;
    var statusmessage = "";
    switch (statusCode)
    {
        case 400:
            statusmessage = "Неверный запрос: запрос не может быть выполнен из-за неправильного синтаксиса";
            break;
        case 401:
            statusmessage = "Отказано в доступе";
            break;
        case 403:
            statusmessage = "Отказано в доступе";
            break;
        case 404:
            statusmessage = "Страницы не существует";
            break;
        case 408:
            statusmessage = "Вышло время ожидания запроса";
            break;
        case 500:
            statusmessage = "Внутренняя ошибка сервера - серверу не удалось завершить обработку запроса";
            break;
        default:
            statusmessage = "Это странно... Произошло то, чего мы не ожидали";
            break;
    }
}
<div class="row">
    <div class="col-2">
        <img src="~/Styles/images/crying_cat.png" alt="Простите:(" width="100%" />
    </div>
    <div class="col-10">
        <h1>Ошибка @Model.StatusCode</h1>
        <h3>@statusmessage</h3>
        @if (Model.ShowRequestId)
        {
            <p>
                Request ID: @Model.RequestId
            </p>
        }
        <center>
            <div class="row">
                <div class="col-auto">
                    <a href="@Model.ReturnUrl" class="btn btn-outline-primary" role="button">&laquo Назад</a>
                </div>
                <div class="col-auto">
                    <a href="/" class="btn btn-outline-primary" role="button">&laquo На главную</a>
                </div>
            </div>
        </center>
    </div>
</div>

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_LayoutNavbar.cshtml";
}
<div class="@(User.Identity.IsAuthenticated ? "container-fluid" : "container") body-content">
    <div class="row">
        <div class="col-12 col-md-auto dont-collapse-sm collapse" id="sidebarSupportedContent">
            <div class="sidebar sticky-top" style="top:74px;">@await Component.InvokeAsync("Sidebar")</div>
        </div>
        <div class="col-12 col-md shadow-lg p-3 rounded border">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy;@(DateTime.Now.Year > 2018 ? $"2018 - {DateTime.Now.Year}" : $"{DateTime.Now.Year}") TL</p>
            </footer>
            @{
                var linePageGenerationTime = "Страница сгенерирована за";
                var lineMs = "мс";
                var line = $"";
                var Start = Context.Items.ContainsKey("RequestStartedOn") ? Context.Items["RequestStartedOn"] as DateTime? : DateTime.MinValue;
                var Finish = DateTime.Now;
                <div class="text-center">
                    <p class="help-block" style="font-size: 80%">
                        UTC @Finish.ToUniversalTime()
                        <br />
                        LTC @Finish.ToLocalTime()
                        <br />
                        @linePageGenerationTime
                        <strong>@((Finish - (Start ?? DateTime.MinValue)).TotalMilliseconds)</strong> @lineMs
                    </p>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-action="changepath" asp-controller="home" asp-area="" method="post">
                            <input name="path" value="@Context.Request.Path" hidden />
                            <button type="submit" class="btn-sm btn-outline-secondary">Сделать эту страницу главной</button>
                        </form>
                    }
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).find('#sidebarSupportedContent')
                .on('hide.bs.collapse', function () {
                    $('#btn_sidebarSupportedContent')
                        .removeClass('glyphicon-menu-up')
                        .addClass('glyphicon-menu-down')
                })
                .on('show.bs.collapse', function () {
                    $('#btn_sidebarSupportedContent')
                        .removeClass('glyphicon-menu-down')
                        .addClass('glyphicon-menu-up')
                });
            if ($('.sidebar').children().is(':empty')) {
                $('.sidebar').parent().remove();
                $('#sidebarSupportedContentButton').remove();
            }
        });
    </script>
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_LayoutNavbar.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSafe.cshtml";
}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm rounded">
    <a class="navbar-brand brandlabel col-auto" href="~/">
        <img src="~/Styles/images/logo_tl.ico" width="40" height="40" class="d-inline-block align-top" alt="">
    </a>
    <button id="sidebarSupportedContentButton" class="btn btn-light navbar-toggler mr-0" type="button" data-toggle="collapse" data-target="#sidebarSupportedContent"
            aria-controls="sidebarSupportedContent" aria-expanded="true" aria-label="Toggle sidebar">
        <span id="btn_sidebarSupportedContent" class="glyphicon glyphicon-menu-down"></span>
    </button>
    <button id="navbarSupportedContentButton" class="btn btn-light navbar-toggler mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="glyphicon glyphicon-menu-hamburger"></span>
    </button>
    <button id="userNavbarSupportedContentButton" class="btn btn-light navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#userNavbarSupportedContent"
            aria-controls="userNavbarSupportedContent" aria-expanded="false" aria-label="Toggle user navigation">
        <span class="glyphicon glyphicon-user"></span>
    </button>
    <div class="collapse navbar-collapse col" id="navbarSupportedContent">
        @await Component.InvokeAsync("Navbar")
    </div>
    <div class="collapse navbar-collapse col-auto" id="userNavbarSupportedContent">
        @await Component.InvokeAsync("UserNavbar")
    </div>
</nav>
<br />
@RenderBody()
@section Scripts {
    @RenderSection("Scripts", required: false)
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_LayoutNavbarPage.cshtml
@{ 
    Layout = "~/Views/Shared/_LayoutNavbar.cshtml";
}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <a href="/">
            <img src="~/Styles/images/logo_tl.ico" width="64" height="64" alt="">
        </a>
    </div>
    <hr />
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md shadow-lg p-3 rounded border">
            @RenderBody()
        </div>
    </div>
</div>
@section Scripts {
    @RenderSection("Scripts", required: false)
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_LayoutSafe.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @(string.IsNullOrWhiteSpace(ViewData["Title"] as string) ? "" : $"{ViewData["Title"]}") &sdot; TL Engine
    </title>
    @await Component.InvokeAsync("Styles")
    <link rel="icon" type="image/x-icon" href="~/Styles/images/logo_tl.ico">
</head>
<body>
    <div id="status-messages-block" class="status-messages-block"></div>
    @RenderBody()
    @await Component.InvokeAsync("Scripts")
    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('.toast').toast();
        });
    </script>
</body>
</html>

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_LayoutSafePage.cshtml
@{ 
    Layout = "~/Views/Shared/_LayoutSafe.cshtml";
}
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <a href="/" data-toggle="tooltip" data-placement="top" title="На Главную">
            <img src="~/Styles/images/logo_tl.ico" width="64" height="64" alt="">
        </a>
    </div>
    <hr />
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-auto shadow-lg p-3 rounded border">
            @RenderBody()
        </div>
    </div>
</div>
@section Scripts {
    @RenderSection("Scripts", required: false)
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Navbar.cshtml
@model TL.Engine.Web.ViewModels.Shared.LinksViewModel

<ul class="navbar-nav mr-auto">
    @foreach (var item in this.Model.Items)
    {
        <li class="nav-item">
            <partial name="_NavbarItem" model="@item" />
        </li>
    }
</ul>

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_NavbarItem.cshtml
@model TL.Engine.Web.ViewModels.Shared.LinkViewModel

@if (this.Model.Items.Count() > 0)
{
    var id = string.Join("", Guid.NewGuid().ToString().Split('-'));

    <div class="btn-group dropdown">
        @if (Model.IsAvailable)
        {
            <a class="btn btn-link nav-link" href="@Url.Content(Model.Url)" data-toggle="tooltip" data-placement="bottom" title="@Model.Description">
                @Model.Name
            </a>
        }
        else
        {
            <a class="btn btn-link nav-link" href="#" data-toggle="tooltip" data-placement="bottom" title="(Пока недоступно) @Model.Description">
                @Model.Name
                <span class="badge badge-pill badge-danger">Скоро</span>
            </a>
        }
        <button id="@id" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu" aria-labelledby="@id">
            @foreach (var item in this.Model.Items)
            {
                <span class="dropdown-item">
                    @if (item.IsAvailable)
                    {
                        <a class="nav-link" href="@Url.Content(item.Url)" data-toggle="tooltip" data-placement="bottom" title="@item.Description">
                            @item.Name
                        </a>
                    }
                    else
                    {
                        <a class="nav-link" href="#" data-toggle="tooltip" data-placement="bottom" title="(Пока недоступно) @item.Description">
                            @item.Name
                            <span class="badge badge-pill badge-danger">Скоро</span>
                        </a>
                    }
                </span>
            }
        </div>
    </div>
}
else
{
    @if (Model.IsAvailable)
    {
        <a class="btn btn-link nav-link" href="@Url.Content(Model.Url)" data-toggle="tooltip" data-placement="bottom" title="@Model.Description">
            @Model.Name
        </a>
    }
    else
    {
        <a class="btn btn-link nav-link" href="#" data-toggle="tooltip" data-placement="bottom" title="(Пока недоступно) @Model.Description">
            @Model.Name
            <span class="badge badge-pill badge-danger">Скоро</span>
        </a>
    }
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Script.cshtml
@model TL.Engine.Web.ViewModels.Shared.ScriptViewModel
<script src="@Model.Url"></script>

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Scripts.cshtml
@model TL.Engine.Web.ViewModels.Shared.ScriptsViewModel

@foreach (var script in this.Model.Scripts)
{
    <partial name="_Script" model="@script" />
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_SidebarItem.cshtml
@model TL.Engine.Web.ViewModels.Shared.LinkViewModel

@if (this.Model.Items.Count() > 0)
{
    var id = string.Join("", Guid.NewGuid().ToString().Split('-'));

    <div class="btn-group dropright">
        @if (Model.IsAvailable)
        {
            <a class="nav-link list-group-item" href="@Url.Content(Model.Url)" data-toggle="tooltip" data-placement="right" title="@Model.Description">
                @Model.Name
            </a>
        }
        else
        {
            <a class="nav-link list-group-item" href="#" data-toggle="tooltip" data-placement="right" title="(Пока недоступно) @Model.Description">
                @Model.Name
                <span class="badge badge-pill badge-danger">Скоро</span>
            </a>
        }
        <button id="@id" type="button" class="btn btn-link dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu shadow-sm rounded" aria-labelledby="@id">
            @foreach (var item in this.Model.Items)
            {
                <span class="dropdown-item">
                    @if (item.IsAvailable)
                    {
                        <a class="nav-link" href="@Url.Content(item.Url)" data-toggle="tooltip" data-placement="right" title="@item.Description">
                            @item.Name
                        </a>
                    }
                    else
                    {
                        <a class="nav-link" href="#" data-toggle="tooltip" data-placement="right" title="(Пока недоступно) @item.Description">
                            @item.Name
                            <span class="badge badge-pill badge-danger">Скоро</span>
                        </a>
                    }
                </span>
            }
        </div>
    </div>
}
else
{
    @if (Model.IsAvailable)
    {
        <a class="nav-link list-group-item" href="@Url.Content(Model.Url)" data-toggle="tooltip" data-placement="right" title="@Model.Description">
            @Model.Name
        </a>
    }
    else
    {
        <a class="nav-link list-group-item" href="#" data-toggle="tooltip" data-placement="right" title="(Пока недоступно) @Model.Description">
            @Model.Name
            <span class="badge badge-pill badge-danger">Скоро</span>
        </a>
    }
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Style.cshtml
@model TL.Engine.Web.ViewModels.Shared.StyleViewModel
<link rel="stylesheet" href="@Model.Url" asp-append-version="true" />

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_Styles.cshtml
@model TL.Engine.Web.ViewModels.Shared.StylesViewModel

@foreach (var styleSheet in this.Model.Styles)
{
    <partial name="_Style" model="@styleSheet" />
}

TL.Extensions/Engine/TL.Engine.Web/Views/Shared/_UserNavbarItem.cshtml
@model TL.Engine.Web.ViewModels.Shared.LinkViewModel

@if (Model.IsAvailable)
{
    <a class="dropdown-item" href="@Url.Content(Model.Url)" data-toggle="tooltip" data-placement="left" title="@Model.Description">
        @Model.Name
    </a>
}
else
{
    <a class="dropdown-item" href="#" data-toggle="tooltip" data-placement="left" title="(Пока недоступно) @Model.Description">
        @Model.Name
        <span class="badge badge-pill badge-danger">Скоро</span>
    </a>
}